### ISSUE TITLE
Issue on OSX

### ISSUE THREAD

**Issue by nartz** [LorenzoBettini/junit-swtbot-example#1]
On osx, we get this error:
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:799)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:277)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:268)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:217)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:151)
	at mathutils.ui.MathUtilsWindow.createContents(MathUtilsWindow.java:65)
	at mathutils.ui.MathUtilsWindow.open(MathUtilsWindow.java:40)
	at mathutils.ui.tests.AbstractMathUtilsWindowTest$1.run(AbstractMathUtilsWindowTest.java:35)
	at java.lang.Thread.run(Thread.java:745)

What is the right way to run this on osx? It runs with:

[INFO] Command line:
	[/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=macosx, -Dosgi.ws=cocoa, -Dosgi.arch=x86_64, -XstartOnFirstThread, -Dosgi.clean=true, -jar, /Users/me/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.3.201.v20161025-1711/org.eclipse.equinox.launcher-1.3.201.v20161025-1711.jar, -data, /Users/me/projects/junit-swtbot-example/mathutils.ui.tests/target/work/data, -install, /Users/me/projects/junit-swtbot-example/mathutils.ui.tests/target/work, -configuration, /Users/me/projects/junit-swtbot-example/mathutils.ui.tests/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /Users/me/projects/junit-swtbot-example/mathutils.ui.tests/target/surefire.properties, -nouithread]

Any hints? This seems to work properly on windows. It has something to do with the display thread - but can't pointpoint what exactly - i see it IS using -XstartOnFirstThread. Other than that, not sure.

**Comment by nartz** [comment]
A quick hack to get this to work, is using Display.syncExec around places where display is used.
